services:
  postgres:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: socman_db
      POSTGRES_USER: socman_user
      POSTGRES_PASSWORD: socman_pass
    ports:
      - "5432:5432"
    networks:
      - socman-network

  backend:
    build:
      context: .
      dockerfile: backend/socman_be.Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://socman_user:socman_pass@postgres/socman_db
    depends_on:
      - postgres
    networks:
      - socman-network

  frontend-dev:
    build:
      context: .
      dockerfile: frontend/socman_fe.Dockerfile
      target: dev
    user: 1000:1000
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "4200:4200"
    # depends_on:
    #   - backend
    networks:
      - socman-network
    entrypoint: /bin/sh
    command: -c "npm run start || $( npm i && npm run start )"
    

  frontend-static:
    build:
      context: .
      dockerfile: frontend/socman_fe.Dockerfile
    ports:
      - "5200:80"
    depends_on:
      - backend
    networks:
      - socman-network

networks:
  socman-network:
    driver: bridge

volumes:
  postgres_data:
